name: Interop Golden-Vector Verify

on:
  push:
    branches: [main]
  pull_request:

jobs:
  interop-golden-vector:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set up Rust 1.79
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
          components: clippy, rustfmt

      - name: Cargo build
        run: cargo build --locked

      - name: Cargo test
        run: cargo test --tests --locked

      - name: Cargo clippy
        run: cargo clippy --locked -- -D warnings

      - name: Interop golden vector check
        shell: bash
        run: |
          set -euo pipefail
          LOG_PATH="$RUNNER_TEMP/interop_golden_check.log"
          echo "LOG_PATH=$LOG_PATH" >> "$GITHUB_ENV"
          scripts/ci/interop_golden_check | tee "$LOG_PATH"

      - name: Upload golden vector artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: interop-golden-vector
          path: |
            vectors/stwo/mini/*
            ${{ env.LOG_PATH }}
